{
"list":[
{
"id":"ငယ္စဥ္ကတည္းက သိပၸံဘာသာရပ္မွာ ကမၻာႀကီးလံုးတယ္လို႔ သက္ေသသာဓကမ်ားနဲ႔ သင္ခဲ့ရေပမယ့္ ကမၻာႀကီးျပားတယ္လို႔ မွတ္ယူထားတဲ့လူေတြ ဒီေခတ္ႀကီးထဲမွာ ရိွေနပါေသးတယ္။ အျငင္းပြားမႈေတြၾကားမွာပဲ မၾကာေသးခင္က ဓာတ္ပံုတစ္ပံုက ကမၻာႀကီးျပားေနတယ္လို႔ ယူဆတဲ့လူေတြကို မွားေၾကာင္း ထပ္သက္ေသျပလိုက္ပါတယ္။",
"name":"Item-1",
"img":"https://itpoekar.com/?attachment_id=25532"
},
{
"id":2,
"name":"Item-2",
"img":"https://i2.wp.com/www.techsolpoint.com/wp-content/uploads/2018/04/bg.jpg"
},
{
"id":3,
"name":"Item-3",
"img":"https://i0.wp.com/www.techsolpoint.com/wp-content/uploads/2018/03/google_seo.jpeg"
},
{
"id":4,
"name":"Item-4",
"img":"https://i2.wp.com/www.techsolpoint.com/wp-content/uploads/2018/03/seo.jpeg"
},
{
"id":5,
"name":"Item-5",
"img":"https://4.bp.blogspot.com/-           nrp2ovenoYs/WPXtdu7YjZI/AAAAAAAAAcw/0ZO1oWD3Dz4TNpeJWGkQVF3gI4tmWJ-       NQCLcB/s1600/913518289_5021def7bc_b.jpg"
}
]
}
